/* This file is automatically generated by abi-versions.awk.
   It defines symbols used by shlib-compat.h, which see.  */

#ifndef _ABI_VERSIONS_H
#define _ABI_VERSIONS_H

/* start libBrokenLocale */
#define ABI_libBrokenLocale_GLIBC_2_0	ABI_libBrokenLocale_GLIBC_2_2_5
#define VERSION_libBrokenLocale_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libBrokenLocale_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libBrokenLocale_GLIBC_2_2_5	GLIBC_2.2.5
/* end libBrokenLocale */

/* start libc */
#define ABI_libc_GLIBC_2_0	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_1	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_1	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_1_1	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_1_1	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_1_2	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_1_2	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_1_3	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_1_3	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_1_4	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_1_4	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_2	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_1	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_2_1	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_2	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_2_2	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_3	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_2_3	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_4	ABI_libc_GLIBC_2_2_5
#define VERSION_libc_GLIBC_2_2_4	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libc_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libc_GLIBC_2_2_6	2	/* support GLIBC_2.2.6 */
#define VERSION_libc_GLIBC_2_2_6	GLIBC_2.2.6
#define ABI_libc_GLIBC_2_3	3	/* support GLIBC_2.3 */
#define VERSION_libc_GLIBC_2_3	GLIBC_2.3
#define ABI_libc_GLIBC_2_3_1	4	/* support GLIBC_2.3.1 */
#define VERSION_libc_GLIBC_2_3_1	GLIBC_2.3.1
#define ABI_libc_GLIBC_2_3_2	5	/* support GLIBC_2.3.2 */
#define VERSION_libc_GLIBC_2_3_2	GLIBC_2.3.2
#define ABI_libc_GLIBC_2_3_3	6	/* support GLIBC_2.3.3 */
#define VERSION_libc_GLIBC_2_3_3	GLIBC_2.3.3
#define ABI_libc_GLIBC_2_3_4	7	/* support GLIBC_2.3.4 */
#define VERSION_libc_GLIBC_2_3_4	GLIBC_2.3.4
#define ABI_libc_GLIBC_2_4	8	/* support GLIBC_2.4 */
#define VERSION_libc_GLIBC_2_4	GLIBC_2.4
#define ABI_libc_GLIBC_2_5	9	/* support GLIBC_2.5 */
#define VERSION_libc_GLIBC_2_5	GLIBC_2.5
#define ABI_libc_GLIBC_2_6	10	/* support GLIBC_2.6 */
#define VERSION_libc_GLIBC_2_6	GLIBC_2.6
#define ABI_libc_GLIBC_2_7	11	/* support GLIBC_2.7 */
#define VERSION_libc_GLIBC_2_7	GLIBC_2.7
#define ABI_libc_GLIBC_2_8	12	/* support GLIBC_2.8 */
#define VERSION_libc_GLIBC_2_8	GLIBC_2.8
#define ABI_libc_GLIBC_2_9	13	/* support GLIBC_2.9 */
#define VERSION_libc_GLIBC_2_9	GLIBC_2.9
#define ABI_libc_GLIBC_2_10	14	/* support GLIBC_2.10 */
#define VERSION_libc_GLIBC_2_10	GLIBC_2.10
#define ABI_libc_GLIBC_2_11	15	/* support GLIBC_2.11 */
#define VERSION_libc_GLIBC_2_11	GLIBC_2.11
#define ABI_libc_GLIBC_2_12	16	/* support GLIBC_2.12 */
#define VERSION_libc_GLIBC_2_12	GLIBC_2.12
#define ABI_libc_GLIBC_2_13	17	/* support GLIBC_2.13 */
#define VERSION_libc_GLIBC_2_13	GLIBC_2.13
#define ABI_libc_GLIBC_2_14	18	/* support GLIBC_2.14 */
#define VERSION_libc_GLIBC_2_14	GLIBC_2.14
#define ABI_libc_GLIBC_2_15	19	/* support GLIBC_2.15 */
#define VERSION_libc_GLIBC_2_15	GLIBC_2.15
#define ABI_libc_GLIBC_2_16	20	/* support GLIBC_2.16 */
#define VERSION_libc_GLIBC_2_16	GLIBC_2.16
#define ABI_libc_GLIBC_2_17	21	/* support GLIBC_2.17 */
#define VERSION_libc_GLIBC_2_17	GLIBC_2.17
#define ABI_libc_GLIBC_2_18	22	/* support GLIBC_2.18 */
#define VERSION_libc_GLIBC_2_18	GLIBC_2.18
#define ABI_libc_GLIBC_2_19	23	/* support GLIBC_2.19 */
#define VERSION_libc_GLIBC_2_19	GLIBC_2.19
#define ABI_libc_HURD_CTHREADS_0_3	24	/* support HURD_CTHREADS_0.3 */
#define VERSION_libc_HURD_CTHREADS_0_3	HURD_CTHREADS_0.3
#define ABI_libc_GLIBC_PRIVATE	25	/* support GLIBC_PRIVATE */
#define VERSION_libc_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libc */

/* start libcrypt */
#define ABI_libcrypt_GLIBC_2_0	ABI_libcrypt_GLIBC_2_2_5
#define VERSION_libcrypt_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libcrypt_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libcrypt_GLIBC_2_2_5	GLIBC_2.2.5
/* end libcrypt */

/* start libdl */
#define ABI_libdl_GLIBC_2_0	ABI_libdl_GLIBC_2_2_5
#define VERSION_libdl_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libdl_GLIBC_2_1	ABI_libdl_GLIBC_2_2_5
#define VERSION_libdl_GLIBC_2_1	GLIBC_2.2.5
#define ABI_libdl_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libdl_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libdl_GLIBC_2_3_3	2	/* support GLIBC_2.3.3 */
#define VERSION_libdl_GLIBC_2_3_3	GLIBC_2.3.3
#define ABI_libdl_GLIBC_2_3_4	3	/* support GLIBC_2.3.4 */
#define VERSION_libdl_GLIBC_2_3_4	GLIBC_2.3.4
/* end libdl */

/* start libm */
#define ABI_libm_GLIBC_2_0	ABI_libm_GLIBC_2_2_5
#define VERSION_libm_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libm_GLIBC_2_1	ABI_libm_GLIBC_2_2_5
#define VERSION_libm_GLIBC_2_1	GLIBC_2.2.5
#define ABI_libm_GLIBC_2_2	ABI_libm_GLIBC_2_2_5
#define VERSION_libm_GLIBC_2_2	GLIBC_2.2.5
#define ABI_libm_GLIBC_2_2_3	ABI_libm_GLIBC_2_2_5
#define VERSION_libm_GLIBC_2_2_3	GLIBC_2.2.5
#define ABI_libm_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libm_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libm_GLIBC_2_3	2	/* support GLIBC_2.3 */
#define VERSION_libm_GLIBC_2_3	GLIBC_2.3
#define ABI_libm_GLIBC_2_3_4	3	/* support GLIBC_2.3.4 */
#define VERSION_libm_GLIBC_2_3_4	GLIBC_2.3.4
#define ABI_libm_GLIBC_2_4	4	/* support GLIBC_2.4 */
#define VERSION_libm_GLIBC_2_4	GLIBC_2.4
#define ABI_libm_GLIBC_2_15	5	/* support GLIBC_2.15 */
#define VERSION_libm_GLIBC_2_15	GLIBC_2.15
#define ABI_libm_GLIBC_2_18	6	/* support GLIBC_2.18 */
#define VERSION_libm_GLIBC_2_18	GLIBC_2.18
#define ABI_libm_GLIBC_2_19	7	/* support GLIBC_2.19 */
#define VERSION_libm_GLIBC_2_19	GLIBC_2.19
/* end libm */

/* start libnsl */
#define ABI_libnsl_GLIBC_2_0	ABI_libnsl_GLIBC_2_2_5
#define VERSION_libnsl_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libnsl_GLIBC_2_1	ABI_libnsl_GLIBC_2_2_5
#define VERSION_libnsl_GLIBC_2_1	GLIBC_2.2.5
#define ABI_libnsl_GLIBC_2_2	ABI_libnsl_GLIBC_2_2_5
#define VERSION_libnsl_GLIBC_2_2	GLIBC_2.2.5
#define ABI_libnsl_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libnsl_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnsl */

/* start libnss_compat */
#define ABI_libnss_compat_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_compat_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_compat_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_compat_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_compat */

/* start libnss_dns */
#define ABI_libnss_dns_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_dns_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_dns_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_dns_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_dns */

/* start libnss_db */
#define ABI_libnss_db_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_db_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_db_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_db_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_db */

/* start libnss_files */
#define ABI_libnss_files_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_files_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_files_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_files_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_files */

/* start libnss_hesiod */
#define ABI_libnss_hesiod_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_hesiod_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_hesiod_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_hesiod_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_hesiod */

/* start libnss_nis */
#define ABI_libnss_nis_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_nis_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_nis_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_nis_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_nis */

/* start libnss_nisplus */
#define ABI_libnss_nisplus_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_nisplus_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_nisplus_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libnss_nisplus_GLIBC_2_2_5	GLIBC_2.2.5
/* end libnss_nisplus */

/* start libpthread */
#define ABI_libpthread_GLIBC_2_0	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_1	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_1	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_1_1	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_1_1	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_1_2	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_1_2	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_2	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_2	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_2_3	ABI_libpthread_GLIBC_2_2_5
#define VERSION_libpthread_GLIBC_2_2_3	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libpthread_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libpthread_GLIBC_2_2_6	2	/* support GLIBC_2.2.6 */
#define VERSION_libpthread_GLIBC_2_2_6	GLIBC_2.2.6
#define ABI_libpthread_GLIBC_2_3	3	/* support GLIBC_2.3 */
#define VERSION_libpthread_GLIBC_2_3	GLIBC_2.3
#define ABI_libpthread_GLIBC_2_3_2	4	/* support GLIBC_2.3.2 */
#define VERSION_libpthread_GLIBC_2_3_2	GLIBC_2.3.2
#define ABI_libpthread_GLIBC_2_3_3	5	/* support GLIBC_2.3.3 */
#define VERSION_libpthread_GLIBC_2_3_3	GLIBC_2.3.3
#define ABI_libpthread_GLIBC_2_3_4	6	/* support GLIBC_2.3.4 */
#define VERSION_libpthread_GLIBC_2_3_4	GLIBC_2.3.4
#define ABI_libpthread_GLIBC_2_4	7	/* support GLIBC_2.4 */
#define VERSION_libpthread_GLIBC_2_4	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_6	8	/* support GLIBC_2.6 */
#define VERSION_libpthread_GLIBC_2_6	GLIBC_2.6
#define ABI_libpthread_GLIBC_2_11	9	/* support GLIBC_2.11 */
#define VERSION_libpthread_GLIBC_2_11	GLIBC_2.11
#define ABI_libpthread_GLIBC_2_12	10	/* support GLIBC_2.12 */
#define VERSION_libpthread_GLIBC_2_12	GLIBC_2.12
#define ABI_libpthread_GLIBC_2_18	11	/* support GLIBC_2.18 */
#define VERSION_libpthread_GLIBC_2_18	GLIBC_2.18
#define ABI_libpthread_GLIBC_2_19	12	/* support GLIBC_2.19 */
#define VERSION_libpthread_GLIBC_2_19	GLIBC_2.19
#define ABI_libpthread_GLIBC_PRIVATE	13	/* support GLIBC_PRIVATE */
#define VERSION_libpthread_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libpthread */

/* start libresolv */
#define ABI_libresolv_GLIBC_2_0	ABI_libresolv_GLIBC_2_2_5
#define VERSION_libresolv_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libresolv_GLIBC_2_2	ABI_libresolv_GLIBC_2_2_5
#define VERSION_libresolv_GLIBC_2_2	GLIBC_2.2.5
#define ABI_libresolv_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libresolv_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libresolv_GLIBC_2_3_2	2	/* support GLIBC_2.3.2 */
#define VERSION_libresolv_GLIBC_2_3_2	GLIBC_2.3.2
#define ABI_libresolv_GLIBC_2_9	3	/* support GLIBC_2.9 */
#define VERSION_libresolv_GLIBC_2_9	GLIBC_2.9
#define ABI_libresolv_GLIBC_PRIVATE	4	/* support GLIBC_PRIVATE */
#define VERSION_libresolv_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libresolv */

/* start librt */
#define ABI_librt_GLIBC_2_1	ABI_librt_GLIBC_2_2_5
#define VERSION_librt_GLIBC_2_1	GLIBC_2.2.5
#define ABI_librt_GLIBC_2_2	ABI_librt_GLIBC_2_2_5
#define VERSION_librt_GLIBC_2_2	GLIBC_2.2.5
#define ABI_librt_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_librt_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_librt_GLIBC_2_3	2	/* support GLIBC_2.3 */
#define VERSION_librt_GLIBC_2_3	GLIBC_2.3
#define ABI_librt_GLIBC_2_3_3	3	/* support GLIBC_2.3.3 */
#define VERSION_librt_GLIBC_2_3_3	GLIBC_2.3.3
#define ABI_librt_GLIBC_2_3_4	4	/* support GLIBC_2.3.4 */
#define VERSION_librt_GLIBC_2_3_4	GLIBC_2.3.4
#define ABI_librt_GLIBC_2_4	5	/* support GLIBC_2.4 */
#define VERSION_librt_GLIBC_2_4	GLIBC_2.4
#define ABI_librt_GLIBC_2_7	6	/* support GLIBC_2.7 */
#define VERSION_librt_GLIBC_2_7	GLIBC_2.7
/* end librt */

/* start libutil */
#define ABI_libutil_GLIBC_2_0	ABI_libutil_GLIBC_2_2_5
#define VERSION_libutil_GLIBC_2_0	GLIBC_2.2.5
#define ABI_libutil_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libutil_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libutil_GLIBC_2_9	2	/* support GLIBC_2.9 */
#define VERSION_libutil_GLIBC_2_9	GLIBC_2.9
/* end libutil */

/* start ld */
#define ABI_ld_GLIBC_2_0	ABI_ld_GLIBC_2_2_5
#define VERSION_ld_GLIBC_2_0	GLIBC_2.2.5
#define ABI_ld_GLIBC_2_1	ABI_ld_GLIBC_2_2_5
#define VERSION_ld_GLIBC_2_1	GLIBC_2.2.5
#define ABI_ld_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_ld_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_ld_GLIBC_2_3	2	/* support GLIBC_2.3 */
#define VERSION_ld_GLIBC_2_3	GLIBC_2.3
#define ABI_ld_GLIBC_2_4	3	/* support GLIBC_2.4 */
#define VERSION_ld_GLIBC_2_4	GLIBC_2.4
#define ABI_ld_GLIBC_PRIVATE	4	/* support GLIBC_PRIVATE */
#define VERSION_ld_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end ld */

/* start libthread_db */
#define ABI_libthread_db_GLIBC_2_1_3	ABI_libthread_db_GLIBC_2_2_5
#define VERSION_libthread_db_GLIBC_2_1_3	GLIBC_2.2.5
#define ABI_libthread_db_GLIBC_2_2_3	ABI_libthread_db_GLIBC_2_2_5
#define VERSION_libthread_db_GLIBC_2_2_3	GLIBC_2.2.5
#define ABI_libthread_db_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libthread_db_GLIBC_2_2_5	GLIBC_2.2.5
#define ABI_libthread_db_GLIBC_2_3	2	/* support GLIBC_2.3 */
#define VERSION_libthread_db_GLIBC_2_3	GLIBC_2.3
#define ABI_libthread_db_GLIBC_2_3_3	3	/* support GLIBC_2.3.3 */
#define VERSION_libthread_db_GLIBC_2_3_3	GLIBC_2.3.3
/* end libthread_db */

/* start libanl */
#define ABI_libanl_GLIBC_2_2_3	ABI_libanl_GLIBC_2_2_5
#define VERSION_libanl_GLIBC_2_2_3	GLIBC_2.2.5
#define ABI_libanl_GLIBC_2_2_5	1	/* support GLIBC_2.2.5 */
#define VERSION_libanl_GLIBC_2_2_5	GLIBC_2.2.5
/* end libanl */

/* start libcidn */
#define ABI_libcidn_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libcidn_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libcidn_GLIBC_2_2_5	2	/* support GLIBC_2.2.5 */
#define VERSION_libcidn_GLIBC_2_2_5	GLIBC_2.2.5
/* end libcidn */

#endif /* abi-versions.h */
