/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcsvc/nlm_prot.h"

bool_t
xdr_nlm_stats (XDR *xdrs, nlm_stats *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_holder (XDR *xdrs, nlm_holder *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->exclusive))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->svid))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->oh))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->l_offset))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->l_len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_testrply (XDR *xdrs, nlm_testrply *objp)
{
	register int32_t *buf;

	 if (!xdr_nlm_stats (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case nlm_denied:
		 if (!xdr_nlm_holder (xdrs, &objp->nlm_testrply_u.holder))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_nlm_stat (XDR *xdrs, nlm_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_nlm_stats (xdrs, &objp->stat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_res (XDR *xdrs, nlm_res *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_nlm_stat (xdrs, &objp->stat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_testres (XDR *xdrs, nlm_testres *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_nlm_testrply (xdrs, &objp->stat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_lock (XDR *xdrs, nlm_lock *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->caller_name, LM_MAXSTRLEN))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->fh))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->oh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->svid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->l_offset))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->l_len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_lockargs (XDR *xdrs, nlm_lockargs *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->block))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->exclusive))
		 return FALSE;
	 if (!xdr_nlm_lock (xdrs, &objp->alock))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->reclaim))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_cancargs (XDR *xdrs, nlm_cancargs *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->block))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->exclusive))
		 return FALSE;
	 if (!xdr_nlm_lock (xdrs, &objp->alock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_testargs (XDR *xdrs, nlm_testargs *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->exclusive))
		 return FALSE;
	 if (!xdr_nlm_lock (xdrs, &objp->alock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_unlockargs (XDR *xdrs, nlm_unlockargs *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_nlm_lock (xdrs, &objp->alock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fsh_mode (XDR *xdrs, fsh_mode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fsh_access (XDR *xdrs, fsh_access *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_share (XDR *xdrs, nlm_share *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->caller_name, LM_MAXSTRLEN))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->fh))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->oh))
		 return FALSE;
	 if (!xdr_fsh_mode (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_fsh_access (xdrs, &objp->access))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_shareargs (XDR *xdrs, nlm_shareargs *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_nlm_share (xdrs, &objp->share))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->reclaim))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_shareres (XDR *xdrs, nlm_shareres *objp)
{
	register int32_t *buf;

	 if (!xdr_netobj (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_nlm_stats (xdrs, &objp->stat))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sequence))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nlm_notify (XDR *xdrs, nlm_notify *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, MAXNAMELEN))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}
