/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcsvc/spray.h"

bool_t
xdr_spraytimeval (XDR *xdrs, spraytimeval *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->sec))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->usec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_spraycumul (XDR *xdrs, spraycumul *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->counter))
		 return FALSE;
	 if (!xdr_spraytimeval (xdrs, &objp->clock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sprayarr (XDR *xdrs, sprayarr *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->sprayarr_val, (u_int *) &objp->sprayarr_len, SPRAYMAX))
		 return FALSE;
	return TRUE;
}
